ï»¿#EXTM3U
#EXTINF:-1,FR: FR HD 1
http://xbox.ztv4you.com:25461/live/PD8fkEdbZ5/iz55nL9LQn/5229.ts
#EXTINF:-1,FR: France 5
http://xbox.ztv4you.com:25461/live/PD8fkEdbZ5/iz55nL9LQn/5234.ts
#EXTINF:-1,FR: France 0
http://xbox.ztv4you.com:25461/live/PD8fkEdbZ5/iz55nL9LQn/5230.ts
#EXTINF:-1,FR: Beinsport 3
http://xbox.ztv4you.com:25461/live/PD8fkEdbZ5/iz55nL9LQn/5228.ts
#EXTINF:-1,FR: Beinsport 2
http://xbox.ztv4you.com:25461/live/PD8fkEdbZ5/iz55nL9LQn/5227.ts
#EXTINF:-1,FR: Beinsport 1
http://xbox.ztv4you.com:25461/live/PD8fkEdbZ5/iz55nL9LQn/5226.ts
#EXTINF:-1,FR: M6 HD
http://xbox.ztv4you.com:25461/live/PD8fkEdbZ5/iz55nL9LQn/5238.ts
#EXTINF:-1,FR: Action HD
http://xbox.ztv4you.com:25461/live/PD8fkEdbZ5/iz55nL9LQn/5236.ts

#EXTINF:-1,FR:13eme
http://egyman.net:1978/live/01000/01000/6362.ts
#EXTINF:-1,FR:AB1
http://egyman.net:1978/live/01000/01000/6361.ts
#EXTINF:-1,FR:Canal  Series
http://egyman.net:1978/live/01000/01000/6360.ts
#EXTINF:-1,FR:CANAL_FAMILY
http://egyman.net:1978/live/01000/01000/6359.ts
#EXTINF:-1,FR:CANAL_HD
http://egyman.net:1978/live/01000/01000/6358.ts
#EXTINF:-1,FR:CINE_CLASSIC_HD
http://egyman.net:1978/live/01000/01000/6357.ts
#EXTINF:-1,FR:CINE_FAMIZ HD
http://egyman.net:1978/live/01000/01000/6356.ts
#EXTINF:-1,FR:CINE_FX
http://egyman.net:1978/live/01000/01000/6355.ts
#EXTINF:-1,FR:CINE_POLAR_HD
http://egyman.net:1978/live/01000/01000/6354.ts
#EXTINF:-1,FR:CINE_PREMIER
http://egyman.net:1978/live/01000/01000/6353.ts
#EXTINF:-1,FR:DISNEY_CINEMA_HD
http://egyman.net:1978/live/01000/01000/6352.ts

#EXTINF:-1,FR: 13 EME RUE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/123737.ts
#EXTINF:-1,FR: 13 ME RUE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62343.ts
#EXTINF:-1,FR: 6Ter HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62342.ts
#EXTINF:-1,FR: A LA CARTE 1 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/87485.ts
#EXTINF:-1,FR: A LA CARTE 2 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88634.ts
#EXTINF:-1,FR: A LA CARTE 3 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88635.ts
#EXTINF:-1,FR: A LA CARTE 4 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88636.ts
#EXTINF:-1,FR: A LA CARTE 5 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88637.ts
#EXTINF:-1,FR: A LA CARTE 6 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88638.ts
#EXTINF:-1,FR: A LA CARTE 7 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88639.ts
#EXTINF:-1,FR: A LA CARTE 8 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88640.ts
#EXTINF:-1,FR: A LA CARTE 9 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88641.ts
#EXTINF:-1,FR: A LA CARTE 10 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/87494.ts
#EXTINF:-1,FR: A LA CARTE 11 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88642.ts
#EXTINF:-1,FR: AB 3 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65830.ts
#EXTINF:-1,FR: AB Moteurs HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73668.ts
#EXTINF:-1,FR: AB1 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65831.ts
#EXTINF:-1,FR: Action HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62340.ts
#EXTINF:-1,FR: Africa 24
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88552.ts
#EXTINF:-1,FR: Alsace 20
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65703.ts
#EXTINF:-1,FR: ALTICE STUDIO HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88506.ts
#EXTINF:-1,FR: ANIMAUX FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62339.ts
#EXTINF:-1,FR: Arte HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62338.ts
#EXTINF:-1,FR: ARTE HD FR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/126388.ts
#EXTINF:-1,FR: BBlack Africa
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88596.ts
#EXTINF:-1,FR: BBLACK CARIBBEAN
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103092.ts
#EXTINF:-1,FR: BBlack Classic
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91876.ts
#EXTINF:-1,FR: Be Black TV
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/126244.ts
#EXTINF:-1,FR: beIN Sports HD 1
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62337.ts
#EXTINF:-1,FR: beIN Sports HD 2
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62336.ts
#EXTINF:-1,FR: beIN Sports HD 3
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62335.ts
#EXTINF:-1,FR: beIN Sports HD 4
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/106042.ts
#EXTINF:-1,FR: beIN Sports HD 5
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/119172.ts
#EXTINF:-1,FR: beIN Sports HD 6
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/119173.ts
#EXTINF:-1,FR: beIN Sports HD 7
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/119174.ts
#EXTINF:-1,FR: beIN Sports HD 8
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/119175.ts
#EXTINF:-1,FR: beIN Sports HD 9
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/119176.ts
#EXTINF:-1,FR: beIN Sports HD 10
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/119177.ts
#EXTINF:-1,FR: beIN Sports Max 4 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65672.ts
#EXTINF:-1,FR: beIN Sports Max 5 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65671.ts
#EXTINF:-1,FR: beIN Sports Max 6 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65670.ts
#EXTINF:-1,FR: beIN Sports Max 7 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65669.ts
#EXTINF:-1,FR: beIN Sports Max 8 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65668.ts
#EXTINF:-1,FR: beIN Sports Max 9
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65667.ts
#EXTINF:-1,FR: beIN Sports Max 10
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65666.ts
#EXTINF:-1,FR: Bet etoile HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91886.ts
#EXTINF:-1,FR: BET HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94150.ts
#EXTINF:-1,FR: BFM Business
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96129.ts
#EXTINF:-1,FR: BFM Bussiness
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86370.ts
#EXTINF:-1,FR: BFM FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62333.ts
#EXTINF:-1,FR: BFM PARIS
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103088.ts
#EXTINF:-1,FR: BFM Sport
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65705.ts
#EXTINF:-1,FR: BOING FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65772.ts
#EXTINF:-1,FR: BOOMERAN HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/112758.ts
#EXTINF:-1,FR: BOOMERANG FRANCE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/107588.ts
#EXTINF:-1,FR: Boomerang HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65773.ts
#EXTINF:-1,FR: Boomrang
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/126831.ts
#EXTINF:-1,FR: BOX OFFICE 1 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86373.ts
#EXTINF:-1,FR: BOX OFFICE 2 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86374.ts
#EXTINF:-1,FR: BOX OFFICE 3 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86375.ts
#EXTINF:-1,FR: BOX OFFICE 4 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86376.ts
#EXTINF:-1,FR: BOX OFFICE 5 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86377.ts
#EXTINF:-1,FR: BOX OFFICE 6 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86378.ts
#EXTINF:-1,FR: BRAVA HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88602.ts
#EXTINF:-1,FR: C NEWS HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86379.ts
#EXTINF:-1,FR: C8 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62331.ts
#EXTINF:-1,FR: Canal 8
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88400.ts
#EXTINF:-1,FR: CANAL 6TER HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/126499.ts
#EXTINF:-1,FR: Canal Alpha
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91158.ts
#EXTINF:-1,FR: CANAL CINEMA FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94526.ts
#EXTINF:-1,FR: CANAL Classic
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127012.ts
#EXTINF:-1,FR: CANAL COMEDIE
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120154.ts
#EXTINF:-1,FR: CANAL D
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127013.ts
#EXTINF:-1,FR: CANAL DECALE
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120155.ts
#EXTINF:-1,FR: CANAL EMOTION HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120153.ts
#EXTINF:-1,FR: Canal Famille HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127014.ts
#EXTINF:-1,FR: CANAL FAMILY HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94524.ts
#EXTINF:-1,FR: CANAL Famiz
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127015.ts
#EXTINF:-1,FR: CANAL FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94523.ts
#EXTINF:-1,FR: CANAL FRISSON HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120163.ts
#EXTINF:-1,FR: CANAL J HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/119378.ts
#EXTINF:-1,FR: CANAL M6 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120162.ts
#EXTINF:-1,FR: CANAL NEWS HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/90263.ts
#EXTINF:-1,FR: Canal Play 1
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/87517.ts
#EXTINF:-1,FR: Canal Play 2
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73739.ts
#EXTINF:-1,FR: Canal Play 3
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73740.ts
#EXTINF:-1,FR: Canal Play 4
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73741.ts
#EXTINF:-1,FR: Canal Play 5
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73742.ts
#EXTINF:-1,FR: CANAL PLAY 15
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91891.ts
#EXTINF:-1,FR: CANAL PREMIER HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120161.ts
#EXTINF:-1,FR: CANAL SERIE CLUB HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120164.ts
#EXTINF:-1,FR: CANAL SERIE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94519.ts
#EXTINF:-1,FR: Canal Sport FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/104465.ts
#EXTINF:-1,FR: CANAL SPORT Football
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127020.ts
#EXTINF:-1,FR: CANAL TCM HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120165.ts
#EXTINF:-1,FR: CANAL+ CINEMA FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62330.ts
#EXTINF:-1,FR: CANAL+ Classic
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91149.ts
#EXTINF:-1,FR: CANAL+ DECALE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94525.ts
#EXTINF:-1,FR: CANAL+ D?cale
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62329.ts
#EXTINF:-1,FR: CANAL+ Emotion
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76231.ts
#EXTINF:-1,FR: Canal+ Famille HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91893.ts
#EXTINF:-1,FR: CANAL+ Family HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62328.ts
#EXTINF:-1,FR: CANAL+ Famiz
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96137.ts
#EXTINF:-1,FR: CANAL+ FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62327.ts
#EXTINF:-1,FR: CANAL+ J HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62324.ts
#EXTINF:-1,FR: CANAL+ Premier
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76235.ts
#EXTINF:-1,FR: Canal+ Serie Club
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/116285.ts
#EXTINF:-1,FR: CANAL+ SERIE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62326.ts
#EXTINF:-1,FR: CANAL+ Sport FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/93248.ts
#EXTINF:-1,FR: CANAL+ SPORT Football
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65661.ts
#EXTINF:-1,FR: CANAL+ SPORT Golf HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86382.ts
#EXTINF:-1,FR: CanalPlay 6
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/87523.ts
#EXTINF:-1,FR: CanalPlay 7
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/87524.ts
#EXTINF:-1,FR: CanalPlay 8
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73745.ts
#EXTINF:-1,FR: CanalPlay 9
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73746.ts
#EXTINF:-1,FR: CanalPlay 10
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/87518.ts
#EXTINF:-1,FR: CanalPlay 11
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91887.ts
#EXTINF:-1,FR: CanalPlay 12
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/119178.ts
#EXTINF:-1,FR: CanalPlay 13
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91889.ts
#EXTINF:-1,FR: CanalPlay 14
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91890.ts
#EXTINF:-1,FR: CanalPlay Live
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65765.ts
#EXTINF:-1,FR: CanalPlay Live (Alli?s)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65746.ts
#EXTINF:-1,FR: CanalPlay Live (Assassin's Creed)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65763.ts
#EXTINF:-1,FR: CanalPlay Live (Au nom De Ma Fille)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65762.ts
#EXTINF:-1,FR: CanalPlay Live (Beaut? cach?e)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65761.ts
#EXTINF:-1,FR: CanalPlay Live (Cigarettes et chocolat chaud)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65760.ts
#EXTINF:-1,FR: CanalPlay Live (Cigognes et compagnie)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65735.ts
#EXTINF:-1,FR: CanalPlay Live (Criminel)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65721.ts
#EXTINF:-1,FR: CanalPlay Live (Demain tout commence)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65759.ts
#EXTINF:-1,FR: CanalPlay Live (Doctor Strange)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65747.ts
#EXTINF:-1,FR: CanalPlay Live (Inferno)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65738.ts
#EXTINF:-1,FR: CanalPlay Live (Jack Reacher:Never Go Back)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65744.ts
#EXTINF:-1,FR: CanalPlay Live (Joyeux Bordel)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65770.ts
#EXTINF:-1,FR: CanalPlay Live (Kickboxer-Vengeance)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65734.ts
#EXTINF:-1,FR: CanalPlay Live (L'Ami Fran?ois d'Assise et ses fr?res)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65758.ts
#EXTINF:-1,FR: CanalPlay Live (La Bataille g?ante de boules de neige)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65757.ts
#EXTINF:-1,FR: CanalPlay Live (La Dream Team)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65713.ts
#EXTINF:-1,FR: CanalPlay Live (La Fille de Brest)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65717.ts
#EXTINF:-1,FR: CanalPlay Live (La Folle Histoire de Max et L?on)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65712.ts
#EXTINF:-1,FR: CanalPlay Live (Le Gang des Antillais)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65718.ts
#EXTINF:-1,FR: CanalPlay Live (Le Petit locataire)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65722.ts
#EXTINF:-1,FR: CanalPlay Live (Le Voyage au Groenland)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65719.ts
#EXTINF:-1,FR: CanalPlay Live (Les m?moires d'un assassin international)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65756.ts
#EXTINF:-1,FR: CanalPlay Live (Les Trolls)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65745.ts
#EXTINF:-1,FR: CanalPlay Live (Les T?tes de l'emploi)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65749.ts
#EXTINF:-1,FR: CanalPlay Live (Lion)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65766.ts
#EXTINF:-1,FR: CanalPlay Live (Ma famille t'adore d?j?)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65767.ts
#EXTINF:-1,FR: CanalPlay Live (Mechanic R?surrection)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65720.ts
#EXTINF:-1,FR: CanalPlay Live (MonsterCars)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65755.ts
#EXTINF:-1,FR: CanalPlay Live (Mr Wolff)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65743.ts
#EXTINF:-1,FR: CanalPlay Live (Nocturnal Animals)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65726.ts
#EXTINF:-1,FR: CanalPlay Live (Oppression)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65737.ts
#EXTINF:-1,FR: CanalPlay Live (Papa Ou Maman 2)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65754.ts
#EXTINF:-1,FR: CanalPlay Live (Passengers)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65753.ts
#EXTINF:-1,FR: CanalPlay Live (Premier Contact aka Arrival)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65769.ts
#EXTINF:-1,FR: CanalPlay Live (P?re Fils Th?rapie)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65752.ts
#EXTINF:-1,FR: CanalPlay Live (Radin!)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65740.ts
#EXTINF:-1,FR: CanalPlay Live (Revenger)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65714.ts
#EXTINF:-1,FR: CanalPlay Live (Rogue One A Star Wars Story)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65751.ts
#EXTINF:-1,FR: CanalPlay Live (Rupture pour tous)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65716.ts
#EXTINF:-1,FR: CanalPlay Live (Sausage Party 16ans)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65730.ts
#EXTINF:-1,FR: CanalPlay Live (Suicide Squad)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65729.ts
#EXTINF:-1,FR: CanalPlay Live (Sully)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65741.ts
#EXTINF:-1,FR: CanalPlay Live (Tamara)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65733.ts
#EXTINF:-1,FR: CanalPlay Live (Toro)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65732.ts
#EXTINF:-1,FR: CanalPlay Live (Tous en sc?ne)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65750.ts
#EXTINF:-1,FR: CanalPlay Live (Un Monde entre nous)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65768.ts
#EXTINF:-1,FR: CanalPlay Live (Underworld-Blood Wars)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65748.ts
#EXTINF:-1,FR: CanalPlay Live (Warcraft:Le commencement)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65727.ts
#EXTINF:-1,FR: CanalPlay Live (? fond)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65715.ts
#EXTINF:-1,FR: Cartoon Network FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62323.ts
#EXTINF:-1,FR: CGTN France
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/118092.ts
#EXTINF:-1,FR: Chasse Et Peche HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62322.ts
#EXTINF:-1,FR: CHERIE 25 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62321.ts
#EXTINF:-1,FR: CIN FX
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86393.ts
#EXTINF:-1,FR: Cine Action HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65794.ts
#EXTINF:-1,FR: Cine Classic HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94518.ts
#EXTINF:-1,FR: Cine Club FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/98103.ts
#EXTINF:-1,FR: Cine Comedie HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65796.ts
#EXTINF:-1,FR: Cine Emotion FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94517.ts
#EXTINF:-1,FR: Cine Famiz FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/100180.ts
#EXTINF:-1,FR: CINE FRISION
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/121510.ts
#EXTINF:-1,FR: Cine Frisson HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/104467.ts
#EXTINF:-1,FR: Cine FX HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62317.ts
#EXTINF:-1,FR: Cine Plus Famiz
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/109091.ts
#EXTINF:-1,FR: Cine Polar HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94515.ts
#EXTINF:-1,FR: Cine Premier FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/95089.ts
#EXTINF:-1,FR: CINE PREMIERE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/119449.ts
#EXTINF:-1,FR: CINE PRIMIER
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/121509.ts
#EXTINF:-1,FR: Cine Star HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65799.ts
#EXTINF:-1,FR: CINE+ CLASSIC HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65800.ts
#EXTINF:-1,FR: CINE+ CLUB HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62320.ts
#EXTINF:-1,FR: CINE+ EMOTION HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62319.ts
#EXTINF:-1,FR: CINE+ FAMILY HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103154.ts
#EXTINF:-1,FR: Cine+ Famiz FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65795.ts
#EXTINF:-1,FR: Cine+ Frisson FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62318.ts
#EXTINF:-1,FR: CINE+ FX
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/112821.ts
#EXTINF:-1,FR: CINE+ isson
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/124474.ts
#EXTINF:-1,FR: CINE+ POLAR HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62316.ts
#EXTINF:-1,FR: Cine+ Premier FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65804.ts
#EXTINF:-1,FR: CINE+ PREMIERE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/90244.ts
#EXTINF:-1,FR: CINEMA BOX OFFICE 1 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/102882.ts
#EXTINF:-1,FR: Cinema Box Office 2
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/114713.ts
#EXTINF:-1,FR: Cinema Box Office 3
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/114714.ts
#EXTINF:-1,FR: Cinema Box Office 4
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/114715.ts
#EXTINF:-1,FR: CinePlus Classic
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96144.ts
#EXTINF:-1,FR: CinePlus Emotion
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96145.ts
#EXTINF:-1,FR: CinePlus Polar
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96147.ts
#EXTINF:-1,FR: CinePlus Premier
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96148.ts
#EXTINF:-1,FR: Clubbing TV
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120001.ts
#EXTINF:-1,FR: CNN International
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/114537.ts
#EXTINF:-1,FR: COMEDIE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/98113.ts
#EXTINF:-1,FR: COMEDIE+ HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76070.ts
#EXTINF:-1,FR: CRIME DISTRICT HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86397.ts
#EXTINF:-1,FR: CRIME INVESTIGATION HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/126500.ts
#EXTINF:-1,FR: CSTAR FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73670.ts
#EXTINF:-1,FR: CSTAR UHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/118979.ts
#EXTINF:-1,FR: CSTARE
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/87534.ts
#EXTINF:-1,FR: D17
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96151.ts
#EXTINF:-1,FR: D8 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86398.ts
#EXTINF:-1,FR: Discovery Channel FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65685.ts
#EXTINF:-1,FR: Discovery Science FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76101.ts
#EXTINF:-1,FR: Disney Channel +1 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/87119.ts
#EXTINF:-1,FR: Disney Channel 1 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/102262.ts
#EXTINF:-1,FR: Disney Channel HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62313.ts
#EXTINF:-1,FR: DISNEY CINEMA FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65786.ts
#EXTINF:-1,FR: DISNEY Cinemagic HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86402.ts
#EXTINF:-1,FR: DISNEY JOUNIR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120837.ts
#EXTINF:-1,FR: DISNEY JUNIOR FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65775.ts
#EXTINF:-1,FR: Disney XD HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62312.ts
#EXTINF:-1,FR: E! Entertainment HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65825.ts
#EXTINF:-1,FR: ELLE GIRL FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88381.ts
#EXTINF:-1,FR: ELLE GIRL FULL HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120814.ts
#EXTINF:-1,FR: Enorme
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96159.ts
#EXTINF:-1,FR: Equidia HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86406.ts
#EXTINF:-1,FR: Equidia Life HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65826.ts
#EXTINF:-1,FR: Equidia Live HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76143.ts
#EXTINF:-1,FR: EQUIPE 21 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/126628.ts
#EXTINF:-1,FR: EURONEWS (FRENCH)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/90262.ts
#EXTINF:-1,FR: Euronews HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65822.ts
#EXTINF:-1,FR: Eurosport 1 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73680.ts
#EXTINF:-1,FR: Eurosport 2 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/74650.ts
#EXTINF:-1,FR: EXTREME SPORTS HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86411.ts
#EXTINF:-1,FR: FASHION TV
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/114551.ts
#EXTINF:-1,FR: FFrance 24 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73682.ts
#EXTINF:-1,FR: FOOT
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120843.ts
#EXTINF:-1,FR: FOOT 24 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/108809.ts
#EXTINF:-1,FR: FOOT 24/24 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127025.ts
#EXTINF:-1,FR: Foot+
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/111076.ts
#EXTINF:-1,FR: Foot+ 24 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103151.ts
#EXTINF:-1,FR: FOOT+ 24/24 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62310.ts
#EXTINF:-1,FR: France 2 FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62308.ts
#EXTINF:-1,FR: France 3 FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62307.ts
#EXTINF:-1,FR: France 4 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62306.ts
#EXTINF:-1,FR: France 5 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62305.ts
#EXTINF:-1,FR: France 24 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/63189.ts
#EXTINF:-1,FR: France Info HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88551.ts
#EXTINF:-1,FR: France ? HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62304.ts
#EXTINF:-1,FR: France24 en
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65702.ts
#EXTINF:-1,FR: France24 FR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/118090.ts
#EXTINF:-1,FR: France24 News
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65823.ts
#EXTINF:-1,FR: GAME ONE FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73683.ts
#EXTINF:-1,FR: GINX TV
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103079.ts
#EXTINF:-1,FR: GOLF CHANNEL HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73684.ts
#EXTINF:-1,FR: GOLF+ HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/112765.ts
#EXTINF:-1,FR: Gong TV
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65701.ts
#EXTINF:-1,FR: GRAND LILLE TV HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/100256.ts
#EXTINF:-1,FR: Grande Lile
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91895.ts
#EXTINF:-1,FR: GULI FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/102267.ts
#EXTINF:-1,FR: Gulli HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62301.ts
#EXTINF:-1,FR: HD 1
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62300.ts
#EXTINF:-1,FR: Histoire HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65686.ts
#EXTINF:-1,FR: I 24 NEWS HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103067.ts
#EXTINF:-1,FR: I24 TV
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/100201.ts
#EXTINF:-1,FR: IL TV
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/114532.ts
#EXTINF:-1,FR: InfoSport HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/100211.ts
#EXTINF:-1,FR: InfoSport+ HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73685.ts
#EXTINF:-1,FR: iTele HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65832.ts
#EXTINF:-1,FR: J-ONE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91898.ts
#EXTINF:-1,FR: KOMBA SPORT HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/107486.ts
#EXTINF:-1,FR: KTO
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91899.ts
#EXTINF:-1,FR: L EQUIPE 21 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73758.ts
#EXTINF:-1,FR: L Equipe HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86420.ts
#EXTINF:-1,FR: L HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120851.ts
#EXTINF:-1,FR: L histoire
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76086.ts
#EXTINF:-1,FR: La Chaine Normande
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65700.ts
#EXTINF:-1,FR: La Chaine Normandie
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91901.ts
#EXTINF:-1,FR: La Tele
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91174.ts
#EXTINF:-1,FR: La Une
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96176.ts
#EXTINF:-1,FR: LCI HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73686.ts
#EXTINF:-1,FR: LCP 100%
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103066.ts
#EXTINF:-1,FR: LCP HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65819.ts
#EXTINF:-1,FR: LCP/PUBLIC SENAT
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103013.ts
#EXTINF:-1,FR: Leman Bleu
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91175.ts
#EXTINF:-1,FR: LUCKY JACK
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91902.ts
#EXTINF:-1,FR: LUXE TV HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88558.ts
#EXTINF:-1,FR: M6 BOUTIQUES
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103062.ts
#EXTINF:-1,FR: M6 FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62296.ts
#EXTINF:-1,FR: M6 Music HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65676.ts
#EXTINF:-1,FR: Ma Chaine Sport
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/100372.ts
#EXTINF:-1,FR: Mangas HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62294.ts
#EXTINF:-1,FR: MCM HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73687.ts
#EXTINF:-1,FR: MCM POP
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94149.ts
#EXTINF:-1,FR: MCM TOP HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86421.ts
#EXTINF:-1,FR: MENS UP
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/114549.ts
#EXTINF:-1,FR: Mezzo HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88605.ts
#EXTINF:-1,FR: MEZZO LIVE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/90261.ts
#EXTINF:-1,FR: Monte Carlo
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91905.ts
#EXTINF:-1,FR: MOTOR SPORT TV HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103380.ts
#EXTINF:-1,FR: Movies 1
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96184.ts
#EXTINF:-1,FR: Movies 2
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76216.ts
#EXTINF:-1,FR: Movies 2 FR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96185.ts
#EXTINF:-1,FR: Movies 3
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76217.ts
#EXTINF:-1,FR: Movies 3 FR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96186.ts
#EXTINF:-1,FR: Movies 4
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127029.ts
#EXTINF:-1,FR: Movies 4 FR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96187.ts
#EXTINF:-1,FR: Movies 5
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127030.ts
#EXTINF:-1,FR: Movies 5 FR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96188.ts
#EXTINF:-1,FR: Movies 6
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127031.ts
#EXTINF:-1,FR: Movies 6 FR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96189.ts
#EXTINF:-1,FR: Movies 7 FR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96190.ts
#EXTINF:-1,FR: MTV Base
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88592.ts
#EXTINF:-1,FR: MTV Classic
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/124488.ts
#EXTINF:-1,FR: MTV HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65695.ts
#EXTINF:-1,FR: MTV HIST
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/100169.ts
#EXTINF:-1,FR: MTV HITS FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65694.ts
#EXTINF:-1,FR: MTV Music
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/101140.ts
#EXTINF:-1,FR: MTV Rocks
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/124486.ts
#EXTINF:-1,FR: MY CUISINE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/105284.ts
#EXTINF:-1,FR: NAT GEO HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62290.ts
#EXTINF:-1,FR: NAT GEO Wild HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62291.ts
#EXTINF:-1,FR: Nati Geo wild FR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86422.ts
#EXTINF:-1,FR: Nautical Channel HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/115495.ts
#EXTINF:-1,FR: NICKELODEON 4TEEN HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120865.ts
#EXTINF:-1,FR: nickelodeon HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62289.ts
#EXTINF:-1,FR: Nickelodeon Junior HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65780.ts
#EXTINF:-1,FR: nickelodeon TEEN HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88569.ts
#EXTINF:-1,FR: NORMANDE TV
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/126503.ts
#EXTINF:-1,FR: NRJ 12 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/108964.ts
#EXTINF:-1,FR: NRJ Hits
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/112851.ts
#EXTINF:-1,FR: NT1 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62286.ts
#EXTINF:-1,FR: Numero 23 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73690.ts
#EXTINF:-1,FR: OCS Choc HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62284.ts
#EXTINF:-1,FR: OCS City HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62283.ts
#EXTINF:-1,FR: OCS GEANT HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62282.ts
#EXTINF:-1,FR: OCS GO CINE 1
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103363.ts
#EXTINF:-1,FR: OCS Go Cine 2 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/102862.ts
#EXTINF:-1,FR: OCS GO CINE 3
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103365.ts
#EXTINF:-1,FR: OCS GO CINE 4
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103366.ts
#EXTINF:-1,FR: OCS GO CINE 5
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103367.ts
#EXTINF:-1,FR: OCS Max HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62281.ts
#EXTINF:-1,FR: OFIVE TV
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103095.ts
#EXTINF:-1,FR: OL TV HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103393.ts
#EXTINF:-1,FR: OLTV HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96203.ts
#EXTINF:-1,FR: OM TV HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103394.ts
#EXTINF:-1,FR: ONE TV HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120842.ts
#EXTINF:-1,FR: ORANGE ACTION
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/87561.ts
#EXTINF:-1,FR: Orange Cine Geants
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/102876.ts
#EXTINF:-1,FR: Orange Cinema ACTION
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94503.ts
#EXTINF:-1,FR: Orange Cinema Aventure
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94502.ts
#EXTINF:-1,FR: Orange Cinema CEst Fait
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96205.ts
#EXTINF:-1,FR: Orange Cinema HORREUR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/94497.ts
#EXTINF:-1,FR: Paramount Channel HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62279.ts
#EXTINF:-1,FR: Paris Premier
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76256.ts
#EXTINF:-1,FR: Paris Premiere HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62278.ts
#EXTINF:-1,FR: Piwi HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65785.ts
#EXTINF:-1,FR: PIWI HD2
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127037.ts
#EXTINF:-1,FR: Piwi plus
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86430.ts
#EXTINF:-1,FR: Piwi+ HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/107589.ts
#EXTINF:-1,FR: PIWI+ HD2
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/107590.ts
#EXTINF:-1,FR: Planete A&E HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127039.ts
#EXTINF:-1,FR: PLANETE CI HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/104651.ts
#EXTINF:-1,FR: PLANETE FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/98126.ts
#EXTINF:-1,FR: Planete+ A&E HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62275.ts
#EXTINF:-1,FR: Planete+ CI HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73692.ts
#EXTINF:-1,FR: Planete+ HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62277.ts
#EXTINF:-1,FR: POLAR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/117676.ts
#EXTINF:-1,FR: POLAR+
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/107575.ts
#EXTINF:-1,FR: QVC HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91916.ts
#EXTINF:-1,FR: RFM TV HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/90274.ts
#EXTINF:-1,FR: RMC Decouvert
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/102866.ts
#EXTINF:-1,FR: RMC Decouverte HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62274.ts
#EXTINF:-1,FR: RMC DECOVERTE 24 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/90259.ts
#EXTINF:-1,FR: RMC SPORT 1 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/116454.ts
#EXTINF:-1,FR: RMC Sport 2 FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/116453.ts
#EXTINF:-1,FR: RMC Sport 3 FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/116452.ts
#EXTINF:-1,FR: RMC SPORT 4 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120878.ts
#EXTINF:-1,FR: RMC SPORT 5 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/124914.ts
#EXTINF:-1,FR: Rouge TV HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91187.ts
#EXTINF:-1,FR: RT FRANCE
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103049.ts
#EXTINF:-1,FR: RTL9 FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73693.ts
#EXTINF:-1,FR: RTS 2 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/104607.ts
#EXTINF:-1,FR: RTS Deux HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86434.ts
#EXTINF:-1,FR: RTS LA UN HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65818.ts
#EXTINF:-1,FR: RTS Un HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73695.ts
#EXTINF:-1,FR: Russia Today France
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/118105.ts
#EXTINF:-1,FR: Salle de CINEMA
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127041.ts
#EXTINF:-1,FR: Salle de CINEMA (Les Gardiens de la Galaxie 2)
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65771.ts
#EXTINF:-1,FR: SC HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/102261.ts
#EXTINF:-1,FR: SCIENC ET VIE
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/87568.ts
#EXTINF:-1,FR: Science et Vie HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103057.ts
#EXTINF:-1,FR: SCIENCE&VIE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62270.ts
#EXTINF:-1,FR: Seasons HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73696.ts
#EXTINF:-1,FR: SERIE CLUB HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62268.ts
#EXTINF:-1,FR: SFR ACTION
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/100191.ts
#EXTINF:-1,FR: SFR Comedie
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/105285.ts
#EXTINF:-1,FR: SFR Horreur
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/105286.ts
#EXTINF:-1,FR: SFR Sci-Fi
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/105287.ts
#EXTINF:-1,FR: SFR SPORT 1 FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62267.ts
#EXTINF:-1,FR: SFR SPORT 2 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62266.ts
#EXTINF:-1,FR: SFR SPORT 3 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62265.ts
#EXTINF:-1,FR: SFR Sport 4
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/75227.ts
#EXTINF:-1,FR: SFR SPORT 5 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65662.ts
#EXTINF:-1,FR: SIENCE ET VIE FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127004.ts
#EXTINF:-1,FR: Sundance TV HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103359.ts
#EXTINF:-1,FR: SyFy FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62264.ts
#EXTINF:-1,FR: SyFy FR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86438.ts
#EXTINF:-1,FR: TCM
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96224.ts
#EXTINF:-1,FR: TCM Cinema HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65792.ts
#EXTINF:-1,FR: TeleBielingue
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91193.ts
#EXTINF:-1,FR: TELESUD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/114533.ts
#EXTINF:-1,FR: TELETOON +1 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/107592.ts
#EXTINF:-1,FR: TELETOON 1 HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/127042.ts
#EXTINF:-1,FR: TELETOON HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103070.ts
#EXTINF:-1,FR: TeleToon+ HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62262.ts
#EXTINF:-1,FR: TEVA FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73698.ts
#EXTINF:-1,FR: TF HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/126505.ts
#EXTINF:-1,FR: TF1 FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62260.ts
#EXTINF:-1,FR: TF1 SERIES & FILMS
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91923.ts
#EXTINF:-1,FR: TF1 Series HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103357.ts
#EXTINF:-1,FR: TFX HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91924.ts
#EXTINF:-1,FR: Tiji HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62259.ts
#EXTINF:-1,FR: TMC FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65814.ts
#EXTINF:-1,FR: TMC HD FR
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/120545.ts
#EXTINF:-1,FR: TOONAMI HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103082.ts
#EXTINF:-1,FR: TOUT L HISTOIRE
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/106438.ts
#EXTINF:-1,FR: TOUTE L
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/126412.ts
#EXTINF:-1,FR: TOUTE L HISTOIRE HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73759.ts
#EXTINF:-1,FR: Toute L Historie
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96233.ts
#EXTINF:-1,FR: Trace africa
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91927.ts
#EXTINF:-1,FR: Trace Mizki
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/118095.ts
#EXTINF:-1,FR: Trace Naija
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/118096.ts
#EXTINF:-1,FR: Trace Toca
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/118098.ts
#EXTINF:-1,FR: TRACE TROPICAL HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88594.ts
#EXTINF:-1,FR: Trace Urban HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86443.ts
#EXTINF:-1,FR: TREK HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76090.ts
#EXTINF:-1,FR: TV BREITZ
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/103164.ts
#EXTINF:-1,FR: TV Breizh FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76251.ts
#EXTINF:-1,FR: TV5
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/107573.ts
#EXTINF:-1,FR: TV5 FR BE SU
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/114530.ts
#EXTINF:-1,FR: TV5 Info
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91190.ts
#EXTINF:-1,FR: TV5 Monde Europe HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86445.ts
#EXTINF:-1,FR: TV5 Monde FBS HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/86446.ts
#EXTINF:-1,FR: TV5 Monde HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65824.ts
#EXTINF:-1,FR: TV5 Monde Info
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/118100.ts
#EXTINF:-1,FR: TV8 Mont Blanc
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91191.ts
#EXTINF:-1,FR: TVM3
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/88550.ts
#EXTINF:-1,FR: T?va
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/107463.ts
#EXTINF:-1,FR: Ushuaia HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/73700.ts
#EXTINF:-1,FR: USHUIA HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/102280.ts
#EXTINF:-1,FR: VH1
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/96236.ts
#EXTINF:-1,FR: VIRGIN HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76046.ts
#EXTINF:-1,FR: Virgin HD Musik
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/65708.ts
#EXTINF:-1,FR: Virgin radio tv
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91928.ts
#EXTINF:-1,FR: VOSGES TV
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/114535.ts
#EXTINF:-1,FR: VOYAGE B
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/87582.ts
#EXTINF:-1,FR: Voyage FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62255.ts
#EXTINF:-1,FR: W9 FHD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/62253.ts
#EXTINF:-1,FR: WEO HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/91930.ts
#EXTINF:-1,FR: ZOUZOU HD
http://landiptv.live:8080/live/Jackyshow200/fe706f2f1493/76123.ts

#EXTINF:-1,FR:M6 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15748.ts
#EXTINF:-1,FR:TF1 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15747.ts
#EXTINF:-1,FR:FRANCE Ã” HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15746.ts
#EXTINF:-1,FR:FRANCE 2 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15745.ts
#EXTINF:-1,FR:FRANCE 3 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15744.ts
#EXTINF:-1,FR:FRANCE 4 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15743.ts
#EXTINF:-1,FR:FRANCE 5 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15742.ts
#EXTINF:-1,FR:FRANCE 24 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15741.ts
#EXTINF:-1,FR:SYFY HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15740.ts
#EXTINF:-1,FR:ACTION HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15739.ts
#EXTINF:-1,FR:TVBREIZH HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15738.ts
#EXTINF:-1,FR:TFX HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15737.ts
#EXTINF:-1,FR:TF1 SERIES FILMS HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15736.ts
#EXTINF:-1,FR:AB1 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15735.ts
#EXTINF:-1,FR:ARTE HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15734.ts
#EXTINF:-1,FR:TEVA HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15733.ts
#EXTINF:-1,FR:CHERIE 25 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15732.ts
#EXTINF:-1,FR:6TER HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15731.ts
#EXTINF:-1,FR:RTL 9 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15730.ts
#EXTINF:-1,FR:NRJ12 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15729.ts
#EXTINF:-1,FR:C NEWS HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15728.ts
#EXTINF:-1,FR:LCI HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15727.ts
#EXTINF:-1,FR:C8 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15726.ts
#EXTINF:-1,FR:W9 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15725.ts
#EXTINF:-1,FR:CSTAR HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15724.ts
#EXTINF:-1,FR:TMC HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15723.ts
#EXTINF:-1,FR:TCM
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15722.ts
#EXTINF:-1,FR:13EME RUE UHD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15721.ts
#EXTINF:-1,FR:BFM TV
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15720.ts
#EXTINF:-1,FR:E! entertainment
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15719.ts
#EXTINF:-1,FR:TV5 MONDE HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15718.ts
#EXTINF:-1,FR:NUMERO 23 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15717.ts
#EXTINF:-1,FR:PARIS PREMIERE HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15716.ts
#EXTINF:-1,FR:PARAMOUNT CHANNEL HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15715.ts
#EXTINF:-1,FR:MCM
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15714.ts
#EXTINF:-1,FR:M6 MUSIC
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15713.ts
#EXTINF:-1,FR:MTV HITS HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15712.ts
#EXTINF:-1,FR:TRACE URBAN
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15711.ts
#EXTINF:-1,FR:MCM TOP
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15710.ts
#EXTINF:-1,FR:MTV
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15709.ts
#EXTINF:-1,FR:NRJ HITS HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15708.ts
#EXTINF:-1,FR:VIRGIN RADIO TV
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15707.ts
#EXTINF:-1,***** FRANCE SPORT *****
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/18396.ts
#EXTINF:-1,FR:FOOT 24 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15705.ts
#EXTINF:-1,FR:EQUIDIA LIVE HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15704.ts
#EXTINF:-1,FR:L EQUIPE 21 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15703.ts
#EXTINF:-1,FR:AB MOTEUR HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15702.ts
#EXTINF:-1,FR:INFO SPORT HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15701.ts
#EXTINF:-1,FR:EUROSPORT 1 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15700.ts
#EXTINF:-1,FR:EUROSPORT 2 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15699.ts
#EXTINF:-1,FR:RMC SPORT 1 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15698.ts
#EXTINF:-1,FR:RMC SPORT 2 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15697.ts
#EXTINF:-1,FR:RMC SPORT 3 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15696.ts
#EXTINF:-1,FR:BEINSPORT 1 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15695.ts
#EXTINF:-1,FR:BEINSPORT 2 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15694.ts
#EXTINF:-1,FR:BEINSPORT 3 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15693.ts
#EXTINF:-1,FR:BEINSPORT 4 MAX
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15692.ts
#EXTINF:-1,FR:BEINSPORT 5 MAX
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15691.ts
#EXTINF:-1,FR:BEINSPORT 6 MAX
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15690.ts
#EXTINF:-1,FR:BEINSPORT 7 MAX
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15689.ts
#EXTINF:-1,*****FRANCE DOCUMENTAIRE*****
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/18397.ts
#EXTINF:-1,FR:SEASONS
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15687.ts
#EXTINF:-1,FR:TREK HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15686.ts
#EXTINF:-1,FR:HISTOIRE
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15685.ts
#EXTINF:-1,FR:ANIMAUX UHD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15684.ts
#EXTINF:-1,FR:USHUAIA TV UHD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15683.ts
#EXTINF:-1,FR:SCIENCE&VIE HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15682.ts
#EXTINF:-1,FR:RMC DECOUVERTE HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15681.ts
#EXTINF:-1,FR:CHASSE & PECHE HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15680.ts
#EXTINF:-1,FR:NAT GEOGRAPHIC HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15679.ts
#EXTINF:-1,FR:NAT GEO WILD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15678.ts
#EXTINF:-1,FR:DISCOVERY SD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15677.ts
#EXTINF:-1,FR:DISCOVERY HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15676.ts
#EXTINF:-1,FR:DISCOVERY SCIENCE HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15675.ts
#EXTINF:-1,FR:PLANET  HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15674.ts
#EXTINF:-1,FR:PLANET  CI HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15673.ts
#EXTINF:-1,FR:PLANET  A&E HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15672.ts
#EXTINF:-1,*****FRANCE ENFANTS*****
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/18398.ts
#EXTINF:-1,FR:PIWI
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15670.ts
#EXTINF:-1,FR:GULLI
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15669.ts
#EXTINF:-1,FR:BOING
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15668.ts
#EXTINF:-1,FR:Disney XD HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15667.ts
#EXTINF:-1,FR:CANAL J UHD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15666.ts
#EXTINF:-1,FR:MANGAS HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15665.ts
#EXTINF:-1,FR:GAME ONE SD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15664.ts
#EXTINF:-1,FR:BOOMERANG  HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15663.ts
#EXTINF:-1,FR:DISNEY CINEMA HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15662.ts
#EXTINF:-1,FR:TELETOON  1 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15661.ts
#EXTINF:-1,FR:NICKELODEON HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15660.ts
#EXTINF:-1,FR:DISNEY JUNIOR HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15659.ts
#EXTINF:-1,FR:DISNEY CHANNEL HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15658.ts
#EXTINF:-1,FR:CARTOON NETWORK HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15657.ts
#EXTINF:-1,*****FRANCE CINEMA*****
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/18399.ts
#EXTINF:-1,FR:CANAL  HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15655.ts
#EXTINF:-1,FR:CANAL FAMILY HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15654.ts
#EXTINF:-1,FR:CANAL SERIES HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15653.ts
#EXTINF:-1,FR:CANAL CINEMA HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15652.ts
#EXTINF:-1,FR:CANAL DECALE HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15651.ts
#EXTINF:-1,FR:CANAL SPORT HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15650.ts
#EXTINF:-1,FR:CINE CLASSIC HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15649.ts
#EXTINF:-1,FR:CINE FRISSON HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15648.ts
#EXTINF:-1,FR:CINE PREMIER  HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15647.ts
#EXTINF:-1,FR:CINE FAMIZ HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15646.ts
#EXTINF:-1,FR:CINE EMOTION  HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15645.ts
#EXTINF:-1,FR:CINE FX HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15644.ts
#EXTINF:-1,FR:OCS MAX HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15643.ts
#EXTINF:-1,FR:OCS CITY HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15642.ts
#EXTINF:-1,FR:OCS CHOC HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15641.ts
#EXTINF:-1,FR:OCS GEANTS HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15640.ts
#EXTINF:-1,FR:COMEDIE   HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15639.ts
#EXTINF:-1,FR:SERIE CLUB HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15638.ts
#EXTINF:-1,FR:beIN OFFICE 1 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15637.ts
#EXTINF:-1,FR:beIN OFFICE 2 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15636.ts
#EXTINF:-1,FR:beIN OFFICE 3 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15635.ts
#EXTINF:-1,FR:beIN OFFICE 4 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15634.ts
#EXTINF:-1,FR:beIN OFFICE 5 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15633.ts
#EXTINF:-1,FR:A LA CARTE 6 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15632.ts
#EXTINF:-1,FR:A LA CARTE 7 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15631.ts
#EXTINF:-1,FR:A LA CARTE 8 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15630.ts
#EXTINF:-1,FR:A LA CARTE 9 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15629.ts
#EXTINF:-1,FR:A LA CARTE 10 HD
http://portal.germanyservers.de:8000/live/dHuhSdjAH0/BRMtQJ21Eq/15628.ts

#EXTINF:-1,FR:13eme
http://egyman.net:1978/live/ahmed1/ahmed2/6362.ts
#EXTINF:-1,FR:AB1
http://egyman.net:1978/live/ahmed1/ahmed2/6361.ts
#EXTINF:-1,FR:Canal  Series
http://egyman.net:1978/live/ahmed1/ahmed2/6360.ts
#EXTINF:-1,FR:CANAL_FAMILY
http://egyman.net:1978/live/ahmed1/ahmed2/6359.ts
#EXTINF:-1,FR:CANAL_HD
http://egyman.net:1978/live/ahmed1/ahmed2/6358.ts
#EXTINF:-1,FR:CINE_CLASSIC_HD
http://egyman.net:1978/live/ahmed1/ahmed2/6357.ts
#EXTINF:-1,FR:CINE_FAMIZ HD
http://egyman.net:1978/live/ahmed1/ahmed2/6356.ts
#EXTINF:-1,FR:CINE_FX
http://egyman.net:1978/live/ahmed1/ahmed2/6355.ts
#EXTINF:-1,FR:CINE_POLAR_HD
http://egyman.net:1978/live/ahmed1/ahmed2/6354.ts
#EXTINF:-1,FR:CINE_PREMIER
http://egyman.net:1978/live/ahmed1/ahmed2/6353.ts
#EXTINF:-1,FR:DISNEY_CINEMA_HD
http://egyman.net:1978/live/ahmed1/ahmed2/6352.ts

#EXTINF:-1,FR::BeIN Sport 1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/715.ts
#EXTINF:-1,FR::BeIN Sport 2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/712.ts
#EXTINF:-1,FR::BeIN Sport 3
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/709.ts
#EXTINF:-1,FR::BeIN_SPORT_1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/714.ts
#EXTINF:-1,FR::BeIN_SPORT_1_S2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/713.ts
#EXTINF:-1,FR::BeIN_SPORT_2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/711.ts
#EXTINF:-1,FR::BeIN_SPORT_2_(b)
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/710.ts
#EXTINF:-1,FR::BeIN_SPORT_3
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/708.ts
#EXTINF:-1,FR::BeIN_SPORT_3_S2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/707.ts
#EXTINF:-1,FR::BeIN_SPORT_MAX4
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/706.ts
#EXTINF:-1,FR::BeIN_SPORT_MAX5
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/705.ts
#EXTINF:-1,FR::BeIN_SPORT_MAX6
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/704.ts
#EXTINF:-1,FR::BeIN_SPORT_MAX7
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/703.ts
#EXTINF:-1,FR::BeIN_SPORT_MAX8
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/702.ts
#EXTINF:-1,FR::BeIN_SPORT_MAX9
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/701.ts
#EXTINF:-1,FR::BeIN_SPORT_MAX10
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/700.ts
#EXTINF:-1,FR::EuroSport
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/696.ts
#EXTINF:-1,FR::EuroSport 2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/694.ts
#EXTINF:-1,FR::EUROSPORT_1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/695.ts
#EXTINF:-1,FR::EUROSPORT_2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/693.ts
#EXTINF:-1,FR::SFR_SPORT_1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/722.ts
#EXTINF:-1,FR::SFR_SPORT_1_S2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/721.ts
#EXTINF:-1,FR::SFR_SPORT_3
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/718.ts
#EXTINF:-1,FR::SFR_SPORT_3_S2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/717.ts
#EXTINF:-1,FR::SFR_SPORT_5
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/716.ts
#EXTINF:-1,FR::Sfr Sport 1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/725.ts
#EXTINF:-1,FR::SFR SPORT 2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/720.ts
#EXTINF:-1,FR::SFR SPORT 2 S2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/719.ts
#EXTINF:-1,FR::Sfr Sport 3
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/724.ts
#EXTINF:-1,FR::Sfr Sport 5
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/723.ts
#EXTINF:-1,FR::AB Moteurs
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/689.ts
#EXTINF:-1,FR::BFM_Sport
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/692.ts
#EXTINF:-1,FR::Canal  Sport
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/699.ts
#EXTINF:-1,FR::CANAL _SPORT
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/698.ts
#EXTINF:-1,FR::EQUIDIA LIVE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/687.ts
#EXTINF:-1,FR::EQUIDIA_LIFE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/686.ts
#EXTINF:-1,FR::FOOT
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/697.ts
#EXTINF:-1,FR::GOLF
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/684.ts
#EXTINF:-1,FR::Golf Channel
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/685.ts
#EXTINF:-1,FR::INFOSPORT
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/688.ts
#EXTINF:-1,FR::L.EQUIPE21
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/690.ts
#EXTINF:-1,FR::LEquipe 21
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/691.ts
#EXTINF:-1,==~~FILMS.FRANCE~~==
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/787.ts
#EXTINF:-1,FR::CANAL
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/786.ts
#EXTINF:-1,FR::Canal  Decale
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/783.ts
#EXTINF:-1,FR::Canal  Emotion
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/773.ts
#EXTINF:-1,FR::Canal  Family
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/781.ts
#EXTINF:-1,FR::Canal  Premier
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/777.ts
#EXTINF:-1,FR::Canal  Series
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/779.ts
#EXTINF:-1,FR::CANAL _CINEMA
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/784.ts
#EXTINF:-1,FR::CANAL _DECALE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/782.ts
#EXTINF:-1,FR::CANAL _FAMILY
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/780.ts
#EXTINF:-1,FR::CANAL _SERIES
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/778.ts
#EXTINF:-1,FR::Canal Cinema
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/785.ts
#EXTINF:-1,FR::Cine  Frisson
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/775.ts
#EXTINF:-1,FR::CINE _CLASSIC
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/771.ts
#EXTINF:-1,FR::CINE _FAMIZ
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/769.ts
#EXTINF:-1,FR::CINE _FRISSON_?
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/774.ts
#EXTINF:-1,FR::CINE _POLAR
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/765.ts
#EXTINF:-1,FR::Cine Classic
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/772.ts
#EXTINF:-1,FR::Cine Famiz
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/770.ts
#EXTINF:-1,FR::Cine Fx
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/768.ts
#EXTINF:-1,FR::Cine Polar
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/766.ts
#EXTINF:-1,FR::CINE_EMOTION
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/776.ts
#EXTINF:-1,FR::CINE_Fx
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/767.ts
#EXTINF:-1,FR::CINE_PREMIER
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/764.ts
#EXTINF:-1,FR::Orange Cine 1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/742.ts
#EXTINF:-1,FR::Orange Cine 2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/741.ts
#EXTINF:-1,FR::Orange Cine 3
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/740.ts
#EXTINF:-1,FR::Orange Cine 4
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/739.ts
#EXTINF:-1,FR::Orange Cine 5
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/738.ts
#EXTINF:-1,FR::Orange Cine 6
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/737.ts
#EXTINF:-1,FR::Orange Cine 7
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/736.ts
#EXTINF:-1,FR::Orange Cine 8
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/735.ts
#EXTINF:-1,FR::Movies 2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/758.ts
#EXTINF:-1,FR::Movies 3
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/759.ts
#EXTINF:-1,FR::Ocs Choc
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/757.ts
#EXTINF:-1,FR::Ocs City
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/755.ts
#EXTINF:-1,FR::Ocs Geant
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/753.ts
#EXTINF:-1,FR::Ocs Max
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/751.ts
#EXTINF:-1,FR::OCS_CHOC
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/756.ts
#EXTINF:-1,FR::OCS_CITY
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/754.ts
#EXTINF:-1,FR::OCS_GEANTS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/752.ts
#EXTINF:-1,FR::OCS_MAX
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/750.ts
#EXTINF:-1,FR::Paramount
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/761.ts
#EXTINF:-1,FR::PARAMOUNT CHANNEL
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/760.ts
#EXTINF:-1,FR::PPV_A_LA_CARTE_1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/734.ts
#EXTINF:-1,FR::PPV_A_LA_CARTE_2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/733.ts
#EXTINF:-1,FR::PPV_A_LA_CARTE_3
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/732.ts
#EXTINF:-1,FR::PPV_A_LA_CARTE_4
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/731.ts
#EXTINF:-1,FR::PPV_A_LA_CARTE_5
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/730.ts
#EXTINF:-1,FR::PPV_A_LA_CARTE_6
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/729.ts
#EXTINF:-1,FR::PPV_A_LA_CARTE_7
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/728.ts
#EXTINF:-1,FR::PPV_A_LA_CARTE_8
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/727.ts
#EXTINF:-1,FR::Tcm Cinema
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/762.ts
#EXTINF:-1,FR::TCM_CINEMA
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/763.ts
#EXTINF:-1,F::-13EME RUE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8129.ts
#EXTINF:-1,F::-6TER
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8146.ts
#EXTINF:-1,F::-A
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8082.ts
#EXTINF:-1,F::-A-LA-CARTE-10
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7963.ts
#EXTINF:-1,F::-A-LA-CARTE-11
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7962.ts
#EXTINF:-1,F::-A-LA-CARTE-12
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7961.ts
#EXTINF:-1,F::-A-LA-CARTE-13
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7960.ts
#EXTINF:-1,F::-A-LA-CARTE-14
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7959.ts
#EXTINF:-1,F::-A-LA-CARTE-15
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7958.ts
#EXTINF:-1,F::-A-LA-CARTE-16
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7957.ts
#EXTINF:-1,F::-A-LA-CARTE-17
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7956.ts
#EXTINF:-1,F::-A-LA-CARTE-18
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7955.ts
#EXTINF:-1,F::-A-LA-CARTE-19
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7954.ts
#EXTINF:-1,F::-A-LA-CARTE-20
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7953.ts
#EXTINF:-1,F::-A-LA-CARTE-21
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7952.ts
#EXTINF:-1,F::-A-LA-CARTE-22
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7951.ts
#EXTINF:-1,F::-A-LA-CARTE-23
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7950.ts
#EXTINF:-1,F::-A-LA-CARTE-24
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7949.ts
#EXTINF:-1,F::-A-LA-CARTE-25
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7948.ts
#EXTINF:-1,F::-A-LA-CARTE-26
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7947.ts
#EXTINF:-1,F::-A-LA-CARTE-27
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7946.ts
#EXTINF:-1,F::-A-LA-CARTE-28
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7945.ts
#EXTINF:-1,F::-A-LA-CARTE-29
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7944.ts
#EXTINF:-1,F::-A-LA-CARTE-3
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7970.ts
#EXTINF:-1,F::-A-LA-CARTE-30
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7943.ts
#EXTINF:-1,F::-A-LA-CARTE-31
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7942.ts
#EXTINF:-1,F::-A-LA-CARTE-32
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7941.ts
#EXTINF:-1,F::-A-LA-CARTE-33
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7940.ts
#EXTINF:-1,F::-A-LA-CARTE-34
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7939.ts
#EXTINF:-1,F::-A-LA-CARTE-35
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7938.ts
#EXTINF:-1,F::-A-LA-CARTE-36
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7937.ts
#EXTINF:-1,F::-A-LA-CARTE-38
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7935.ts
#EXTINF:-1,F::-A-LA-CARTE-39
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7934.ts
#EXTINF:-1,F::-A-LA-CARTE-4
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7969.ts
#EXTINF:-1,F::-A-LA-CARTE-40
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7933.ts
#EXTINF:-1,F::-A-LA-CARTE-5
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7968.ts
#EXTINF:-1,F::-A-LA-CARTE-6
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7967.ts
#EXTINF:-1,F::-A-LA-CARTE-7
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7966.ts
#EXTINF:-1,F::-A-LA-CARTE-8
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7965.ts
#EXTINF:-1,F::-A-LA-CARTE-9
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7964.ts
#EXTINF:-1,F::-AB MOTEURS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8049.ts
#EXTINF:-1,F::-AB1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8091.ts
#EXTINF:-1,F::-ACTION
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8110.ts
#EXTINF:-1,F::-ALTICE STUDIO
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8130.ts
#EXTINF:-1,F::-ANIMAUX
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8027.ts
#EXTINF:-1,F::-ARTE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8148.ts
#EXTINF:-1,F::-BABY TV
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7991.ts
#EXTINF:-1,F::-BEIN SPORTS 1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8076.ts
#EXTINF:-1,F::-BEIN SPORTS 2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8074.ts
#EXTINF:-1,F::-BEIN SPORTS 3
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8072.ts
#EXTINF:-1,F::-BEIN SPORTS MAX 10
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8064.ts
#EXTINF:-1,F::-BEIN SPORTS MAX 4
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8070.ts
#EXTINF:-1,F::-BEIN SPORTS MAX 5
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8069.ts
#EXTINF:-1,F::-BEIN SPORTS MAX 6
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8068.ts
#EXTINF:-1,F::-BEIN SPORTS MAX 7
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8067.ts
#EXTINF:-1,F::-BEIN SPORTS MAX 8
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8066.ts
#EXTINF:-1,F::-BEIN SPORTS MAX 9
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8065.ts
#EXTINF:-1,F::-BEIN SPORTS1 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8075.ts
#EXTINF:-1,F::-BEIN SPORTS2 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8073.ts
#EXTINF:-1,F::-BEIN SPORTS3 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8071.ts
#EXTINF:-1,F::-BET
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8083.ts
#EXTINF:-1,F::-BFM BUSINESS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7974.ts
#EXTINF:-1,F::-BFM BUSNESS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7980.ts
#EXTINF:-1,F::-BFM PARIS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7975.ts
#EXTINF:-1,F::-BFM SPORT
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8055.ts
#EXTINF:-1,F::-BFM TV
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7981.ts
#EXTINF:-1,F::-BOING
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7987.ts
#EXTINF:-1,F::-BOOMERANG
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7990.ts
#EXTINF:-1,F::-BRAVA
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8010.ts
#EXTINF:-1,F::-C8
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8096.ts
#EXTINF:-1,F::-CANAL
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8136.ts
#EXTINF:-1,F::-CANAL  4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8135.ts
#EXTINF:-1,F::-CANAL  CINEMA 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8133.ts
#EXTINF:-1,F::-CANAL CINEMA
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8134.ts
#EXTINF:-1,F::-CANAL DECALE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8102.ts
#EXTINF:-1,F::-CANAL FAMILY
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8132.ts
#EXTINF:-1,F::-CANAL FAMILY 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8131.ts
#EXTINF:-1,F::-CANAL J
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7988.ts
#EXTINF:-1,F::-CANAL SERIES
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8103.ts
#EXTINF:-1,F::-CANAL SERIES 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8104.ts
#EXTINF:-1,F::-CANAL SPORT
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8078.ts
#EXTINF:-1,F::-CANAL SPORT 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8077.ts
#EXTINF:-1,F::-CARTOON NETWORK
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8005.ts
#EXTINF:-1,F::-CHASSE ET PECHE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8026.ts
#EXTINF:-1,F::-CHERIE 25
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8008.ts
#EXTINF:-1,F::-CINE CLASSIC
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8114.ts
#EXTINF:-1,F::-CINE CLUB
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8113.ts
#EXTINF:-1,F::-CINE EMOTION
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8120.ts
#EXTINF:-1,F::-CINE EMOTION 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8119.ts
#EXTINF:-1,F::-CINE FAMIZ
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8112.ts
#EXTINF:-1,F::-CINE FRESSON 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8115.ts
#EXTINF:-1,F::-CINE FRISSON
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8116.ts
#EXTINF:-1,F::-CINE PREMIER
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8118.ts
#EXTINF:-1,F::-CINE PREMIER 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8117.ts
#EXTINF:-1,F::-Club-RTL
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8107.ts
#EXTINF:-1,F::-CNEWS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7979.ts
#EXTINF:-1,F::-COMEDIE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8100.ts
#EXTINF:-1,F::-Crime District
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8108.ts
#EXTINF:-1,F::-CSTAR
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8093.ts
#EXTINF:-1,F::-DISCOVERY CHANNEL
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8039.ts
#EXTINF:-1,F::-DISCOVERY FAMILY
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8037.ts
#EXTINF:-1,F::-DISCOVERY ID
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8038.ts
#EXTINF:-1,F::-DISCOVERY SCIENCE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8040.ts
#EXTINF:-1,F::-DISNEY CHANNEL
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7997.ts
#EXTINF:-1,F::-Disney Channel 1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7996.ts
#EXTINF:-1,F::-DISNEY CINEMA
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7998.ts
#EXTINF:-1,F::-DISNEY JUNIOR
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7994.ts
#EXTINF:-1,F::-DISNEY XD
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7995.ts
#EXTINF:-1,F::-DJAZZ
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8011.ts
#EXTINF:-1,F::-E !
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8145.ts
#EXTINF:-1,F::-Elevensports1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8059.ts
#EXTINF:-1,F::-ElevenSports2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8058.ts
#EXTINF:-1,F::-ELLE GIRL
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8086.ts
#EXTINF:-1,F::-EQUIDIA LIVE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8048.ts
#EXTINF:-1,F::-EUROSPORT 1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8054.ts
#EXTINF:-1,F::-EUROSPORT 2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8053.ts
#EXTINF:-1,F::-EXTREAM SPORTS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8044.ts
#EXTINF:-1,F::-F::-A-LA-CARTE-37
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7936.ts
#EXTINF:-1,F::-FOOT 24/24
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8050.ts
#EXTINF:-1,F::-FRANCE 2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8156.ts
#EXTINF:-1,F::-FRANCE 2 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8155.ts
#EXTINF:-1,F::-FRANCE 3
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8154.ts
#EXTINF:-1,F::-FRANCE 4
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8153.ts
#EXTINF:-1,F::-FRANCE 5
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8152.ts
#EXTINF:-1,F::-FRANCE O
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8151.ts
#EXTINF:-1,F::-FRANCEINFO:
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7973.ts
#EXTINF:-1,F::-GAME ONE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7985.ts
#EXTINF:-1,F::-GOLF
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8047.ts
#EXTINF:-1,F::-GULLI
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8006.ts
#EXTINF:-1,F::-HD1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8139.ts
#EXTINF:-1,F::-HISTOIRE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8020.ts
#EXTINF:-1,F::-I24 NEWS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7977.ts
#EXTINF:-1,F::-INFOSPORT
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8051.ts
#EXTINF:-1,F::-J-ONE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8000.ts
#EXTINF:-1,F::-L'EQUIPE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8052.ts
#EXTINF:-1,F::-LA CHAINE METEO
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7971.ts
#EXTINF:-1,F::-La Deux
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8141.ts
#EXTINF:-1,F::-La Trois
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7976.ts
#EXTINF:-1,F::-La Une HD
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8142.ts
#EXTINF:-1,F::-LCI
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7982.ts
#EXTINF:-1,F::-LCP
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7972.ts
#EXTINF:-1,F::-M6
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8150.ts
#EXTINF:-1,F::-M6 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8149.ts
#EXTINF:-1,F::-M6 MUSIC
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8015.ts
#EXTINF:-1,F::-MANGAS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7989.ts
#EXTINF:-1,F::-MCM TOP
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8014.ts
#EXTINF:-1,F::-MELODY
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8016.ts
#EXTINF:-1,F::-MOTORSPORT
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8045.ts
#EXTINF:-1,F::-MTV
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8013.ts
#EXTINF:-1,F::-MTV HITS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8017.ts
#EXTINF:-1,F::-MUSEUM
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8029.ts
#EXTINF:-1,F::-MY CUISINE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8030.ts
#EXTINF:-1,F::-MY ZEN TV
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8019.ts
#EXTINF:-1,F::-NAT GEO WILD
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8041.ts
#EXTINF:-1,F::-NATIONAL GEO
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8043.ts
#EXTINF:-1,F::-NATIONAL GEO 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8042.ts
#EXTINF:-1,F::-NICKELODEON
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8004.ts
#EXTINF:-1,F::-NICKELODEON 1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8003.ts
#EXTINF:-1,F::-NICKELODEON 4TEEN
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8002.ts
#EXTINF:-1,F::-NICKELODEON FOR TEEN
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7999.ts
#EXTINF:-1,F::-NICKELODEON JR
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8001.ts
#EXTINF:-1,F::-NOLLYWOOD TV
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8087.ts
#EXTINF:-1,F::-NON STOP PEOPLE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8088.ts
#EXTINF:-1,F::-NOVELAS FR
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8079.ts
#EXTINF:-1,F::-NRJ HITS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8018.ts
#EXTINF:-1,F::-NRJ12
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8009.ts
#EXTINF:-1,F::-NT1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8092.ts
#EXTINF:-1,F::-NUMERO 23
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8095.ts
#EXTINF:-1,F::-OCS CHOC
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8125.ts
#EXTINF:-1,F::-OCS CHOC 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8124.ts
#EXTINF:-1,F::-OCS CITY
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8123.ts
#EXTINF:-1,F::-OCS CITY 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8122.ts
#EXTINF:-1,F::-OCS GEANTS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8121.ts
#EXTINF:-1,F::-OCS MAX
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8127.ts
#EXTINF:-1,F::-OCS MAX 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8126.ts
#EXTINF:-1,F::-ONZEO
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8046.ts
#EXTINF:-1,F::-Orange Cinema 1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7932.ts
#EXTINF:-1,F::-Orange Cinema 10
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7923.ts
#EXTINF:-1,F::-Orange Cinema 2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7931.ts
#EXTINF:-1,F::-Orange Cinema 3
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7930.ts
#EXTINF:-1,F::-Orange Cinema 4
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7929.ts
#EXTINF:-1,F::-Orange Cinema 5
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7928.ts
#EXTINF:-1,F::-Orange Cinema 6
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7927.ts
#EXTINF:-1,F::-Orange Cinema 7
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7926.ts
#EXTINF:-1,F::-Orange Cinema 8
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7925.ts
#EXTINF:-1,F::-Orange Cinema 9
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7924.ts
#EXTINF:-1,F::-PARAMOUNT CHANNEL
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8109.ts
#EXTINF:-1,F::-PARIS PREMIERE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8137.ts
#EXTINF:-1,F::-PIWI
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8007.ts
#EXTINF:-1,F::-PLANET CI 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8035.ts
#EXTINF:-1,F::-PLANETE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8033.ts
#EXTINF:-1,F::-PLANETE A&E
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8034.ts
#EXTINF:-1,F::-PLANETE CI
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8036.ts
#EXTINF:-1,F::-Plug-RTL
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8106.ts
#EXTINF:-1,F::-Polar
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8099.ts
#EXTINF:-1,F::-RFM TV
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8080.ts
#EXTINF:-1,F::-RMC DECOUVERTE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8022.ts
#EXTINF:-1,F::-RTL-TVi HD
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8140.ts
#EXTINF:-1,F::-RTL9
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8090.ts
#EXTINF:-1,F::-RTS Deux HD
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8143.ts
#EXTINF:-1,F::-RTS Un HD
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8144.ts
#EXTINF:-1,F::-SCIENCE ET VIE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8025.ts
#EXTINF:-1,F::-SEASONS
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8024.ts
#EXTINF:-1,F::-Serie club
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8101.ts
#EXTINF:-1,F::-SFR SPORT 1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8063.ts
#EXTINF:-1,F::-SFR SPORT 2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8062.ts
#EXTINF:-1,F::-SFR SPORT 3
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8061.ts
#EXTINF:-1,F::-SFR SPORT 5
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8060.ts
#EXTINF:-1,F::-Sundance
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8089.ts
#EXTINF:-1,F::-SUNDANCE TV
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8081.ts
#EXTINF:-1,F::-SYFY
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8128.ts
#EXTINF:-1,F::-TCM cinema
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8111.ts
#EXTINF:-1,F::-TELETOON
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7993.ts
#EXTINF:-1,F::-TELETOON 1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7992.ts
#EXTINF:-1,F::-TEVA
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8094.ts
#EXTINF:-1,F::-TF1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8158.ts
#EXTINF:-1,F::-TF1 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8157.ts
#EXTINF:-1,F::-TIJI
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7986.ts
#EXTINF:-1,F::-TMC
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8147.ts
#EXTINF:-1,F::-TOONAMI
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7984.ts
#EXTINF:-1,F::-TOUTE L'HISTOIRE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8021.ts
#EXTINF:-1,F::-TRACE AFRICA
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8012.ts
#EXTINF:-1,F::-TREK
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8023.ts
#EXTINF:-1,F::-TV BREIZH
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8138.ts
#EXTINF:-1,F::-TV5 MONDE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/7978.ts
#EXTINF:-1,F::-USHUAIA 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8031.ts
#EXTINF:-1,F::-USHUAIA TV
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8032.ts
#EXTINF:-1,F::-VElevensports1
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8057.ts
#EXTINF:-1,F::-VElevenSports2
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8056.ts
#EXTINF:-1,F::-VICELAND
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8084.ts
#EXTINF:-1,F::-VOYAGE
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8028.ts
#EXTINF:-1,F::-W9
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8098.ts
#EXTINF:-1,F::-W9 4K
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8097.ts
#EXTINF:-1,F::-WARNER TV
#EXTVLCOPT:http-user-agent=Stupied
http://max-iptv2sat.ddns.net:9000/live/asemgOOdsssssalgado/mslakfmklmlndjkfnsjkfnsjk/8085.ts
